- targets:
  - 172.20.1.21:9100
  - 172.20.1.24:9100
  - 172.20.1.25:9100
  - 172.20.1.26:9100
  - 172.20.1.28:9100
  - 172.20.1.29:9100
  - 172.20.1.30:9100
  - 172.20.1.31:9100
  - 172.20.1.23:9100
  - 172.20.1.104:9100
  - 172.20.1.22:9100
  labels:
    job: virtualization